all: os-image.bin

boot.bin: boot.asm
	nasm -f bin boot.asm -o boot.bin

kernel.o: kernel.c
	gcc -ffreestanding -m32 -c kernel.c -o kernel.o

terminal.o: terminal.c
	gcc -ffreestanding -m32 -c terminal.c -o terminal.o

kernel.bin: kernel.o terminal.o
	ld -m elf_i386 -T linker.ld -o kernel.bin kernel.o terminal.o

os-image.bin: boot.bin kernel.bin
	cat boot.bin kernel.bin > os-image.bin

run:
	qemu-system-i386 -drive format=raw,file=os-image.bin

clean:
	rm -f *.bin *.o
